In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import json

import pandas as pd

from gzreduction.vote_sources.panoptes_exports import export_to_responses
from gzreduction.vote_sources.panoptes_exports import aggregate
from gzreduction.schemas.jwst_cosmos_schema import jwst_cosmos_schema

In [3]:

schema = jwst_cosmos_schema

In [4]:
classification_export_loc = '/home/walml/repos/gz-panoptes-reduction/data/jwst_cosmos/jwst-cosmos-classifications.csv'
aggregated_loc = '/home/walml/repos/gz-panoptes-reduction/data/jwst_cosmos/jwst-cosmos_reduced_votes.csv'

In [5]:
# nrows = 10000
nrows = None
clf = pd.read_csv(classification_export_loc, nrows=nrows)
clf

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids
0,634641900,LucyitSwD,4304.0,e52e42c436f09de05bee,28504,JWST COSMOS,2.1,2025-04-28 22:39:28 UTC,NaN,NaN,"{""source"":""api"",""session"":""751c2cda01f911749d6...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108539317"":{""retired"":null,""!RA"":""149.753373...",108539317
1,634643107,LucyitSwD,4304.0,ae3407ea633d9569a6b5,28504,JWST COSMOS,2.1,2025-04-28 22:45:57 UTC,NaN,NaN,"{""source"":""api"",""session"":""751c2cda01f911749d6...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108539318"":{""retired"":null,""!RA"":""149.804200...",108539318
2,634643153,LucyitSwD,4304.0,ae3407ea633d9569a6b5,28504,JWST COSMOS,2.1,2025-04-28 22:46:12 UTC,NaN,NaN,"{""source"":""api"",""session"":""751c2cda01f911749d6...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108539320"":{""retired"":null,""!RA"":""149.925941...",108539320
3,634643391,LucyitSwD,4304.0,ae3407ea633d9569a6b5,28504,JWST COSMOS,2.1,2025-04-28 22:47:34 UTC,NaN,NaN,"{""source"":""api"",""session"":""751c2cda01f911749d6...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108539319"":{""retired"":null,""!RA"":""149.733739...",108539319
4,634692912,allisonava08,2864008.0,44a276b405bbaff91137,28504,JWST COSMOS,2.1,2025-04-29 04:07:02 UTC,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108665729"":{""retired"":{""id"":140555828,""workf...",108665729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344530,644271156,BenjaminMorris,2882338.0,ca81f8ab82e7e8d0301f,28504,JWST COSMOS,2.1,2025-06-04 19:26:08 UTC,NaN,NaN,"{""source"":""api"",""session"":""2cdf2edf7db3a2a716f...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108790242"":{""retired"":null,""!RA"":""150.261802...",108790242
344531,644271219,BenjaminMorris,2882338.0,ca81f8ab82e7e8d0301f,28504,JWST COSMOS,2.1,2025-06-04 19:26:27 UTC,NaN,NaN,"{""source"":""api"",""session"":""2cdf2edf7db3a2a716f...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108722324"":{""retired"":null,""!RA"":""150.209039...",108722324
344532,644271228,OisinCrowe,2873105.0,5f5affb62ede07ff4354,28504,JWST COSMOS,2.1,2025-06-04 19:26:28 UTC,NaN,NaN,"{""source"":""api"",""session"":""9dee80b7cf5cc748bf2...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108769133"":{""retired"":null,""!RA"":""149.910365...",108769133
344533,644271254,laurenkocurek,2882343.0,2175936b6b1643812b61,28504,JWST COSMOS,2.1,2025-06-04 19:26:35 UTC,NaN,NaN,"{""source"":""api"",""session"":""82f4a68b19bff830743...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108974943"":{""retired"":null,""!RA"":""150.020491...",108974943
344534,644271259,OisinCrowe,2873105.0,5f5affb62ede07ff4354,28504,JWST COSMOS,2.1,2025-06-04 19:26:37 UTC,NaN,NaN,"{""source"":""api"",""session"":""9dee80b7cf5cc748bf2...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108882360"":{""retired"":null,""!RA"":""150.392324...",108882360

In [6]:
clf['created_at'] = pd.to_datetime(clf['created_at'])
clf = clf[clf['created_at'] > '2025-04-29']  # live on 29th

In [7]:
clf.iloc[-1]

classification_id                                            644271259
user_name                                                   OisinCrowe
user_id                                                      2873105.0
user_ip                                           5f5affb62ede07ff4354
workflow_id                                                      28504
workflow_name                                              JWST COSMOS
workflow_version                                                   2.1
created_at                                   2025-06-04 19:26:37+00:00
gold_standard                                                      NaN
expert                                                             NaN
metadata             {"source":"api","session":"9dee80b7cf5cc748bf2...
annotations          [{"task":"T0","task_label":"Is the **central g...
subject_data         {"108882360":{"retired":null,"!RA":"150.392324...
subject_ids                                                  108882360
Name: 344534, dtype: object

In [8]:
clf.iloc[-1]['metadata']

'{"source":"api","session":"9dee80b7cf5cc748bf20f70b5782a3048ebed49bd649d4fe3d62074eb4d72681","viewport":{"width":1517,"height":684},"started_at":"2025-06-04T19:26:28.204Z","user_agent":"Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","utc_offset":"25200","finished_at":"2025-06-04T19:26:34.950Z","live_project":true,"interventions":{"opt_in":true,"messageShown":false},"user_language":"en","user_group_ids":[],"subject_dimensions":[{"clientWidth":979,"clientHeight":506,"naturalWidth":1559,"naturalHeight":806},null],"subject_selection_state":{"retired":false,"selected_at":"2025-06-04T19:25:17.110Z","already_seen":false,"selection_state":"normal","finished_workflow":false,"user_has_finished_workflow":false},"workflow_translation_id":"84788"}'

In [9]:
clf.iloc[-1]['subject_data']

'{"108882360":{"retired":null,"!RA":"150.39232405","!Dec":"2.33139896","!radius":"9.038871524387325e-05","!ned_link":"[Click to search NASA NED](+tab+https://ned.ipac.caltech.edu/conesearch?search_type=Near%20Position%20Search\\u0026in_csys=Equatorial\\u0026in_equinox=J2000\\u0026ra=150.39232405d\\u0026dec=2.33139896d\\u0026radius=0.1)","#id_field":"501927_B4","!desi_link":"[Click to view in DESI](+tab+https://www.legacysurvey.org/viewer?ra=150.39232405\\u0026dec=2.33139896\\u0026layer=ls-dr9\\u0026zoom=15)","COSMOS_info":"Thanks to the COSMOS-Web team for their support! [Learn more about COSMOS-Web here.](+tab+https://cosmos.astro.caltech.edu/page/cosmosweb)","!esasky_link":"[Click to view in ESA Sky](+tab+https://sky.esa.int/esasky/?target=150.39232405%2.33139896\\u0026hips=JWST+NIRCam+Imaging\\u0026fov=0.3940858692337921\\u0026projection=TAN\\u0026cooframe=J2000\\u0026sci=false\\u0026lang=en)","!sersic_index":"0.723451018593355","!F444W_magnitude":"24.845845073025068"}}'

In [10]:
clf['created_at'].iloc[0]

Timestamp('2025-04-29 04:07:02+0000', tz='UTC')

In [11]:
def get_jwst_subject_id(subject_data):
    loaded = json.loads(subject_data)
    inner_dict = loaded[list(loaded.keys())[0]]
    # print(inner_dict)
    
    # seems changed?
    status_dict = inner_dict['retired']

    if status_dict is None:
        return None  # not yet retired
    
    try:
        return str(int(status_dict['id']))
    except KeyError:
        try:
            return str(int(status_dict['!id']))
        except KeyError:
            return None

In [12]:
clf.head()

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids
4,634692912,allisonava08,2864008.0,44a276b405bbaff91137,28504,JWST COSMOS,2.1,2025-04-29 04:07:02+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108665729"":{""retired"":{""id"":140555828,""workf...",108665729
5,634692959,allisonava08,2864008.0,42f09ae8d31875c1ec95,28504,JWST COSMOS,2.1,2025-04-29 04:07:27+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108682329"":{""retired"":{""id"":140555845,""workf...",108682329
6,634692987,allisonava08,2864008.0,991590e35312d4bfe394,28504,JWST COSMOS,2.1,2025-04-29 04:07:40+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108657542"":{""retired"":{""id"":140555850,""workf...",108657542
7,634693016,allisonava08,2864008.0,cfeada996e5d09bac3bc,28504,JWST COSMOS,2.1,2025-04-29 04:07:54+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108640888"":{""retired"":{""id"":140555856,""workf...",108640888
8,634693079,allisonava08,2864008.0,9925ccdf788b4bd5b14c,28504,JWST COSMOS,2.1,2025-04-29 04:08:22+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108639693"":{""retired"":{""id"":140555866,""workf...",108639693

In [13]:
workflows = [28504]
clf = clf[clf['workflow_id'].isin(workflows)]  # should be already true, but hey

In [14]:
clf['id_str'] = clf['subject_data'].apply(get_jwst_subject_id)
clf = clf[clf['id_str'].notna()]

In [15]:
clf['id_str'].value_counts(dropna=False)

id_str
140562844    166
140564475    163
140557914    162
140564739    161
140559223    159
            ...
140559195     40
140556237     40
140561677     40
140562699     40
140559984     40
Name: count, Length: 4709, dtype: int64

In [16]:
clf

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids,id_str
4,634692912,allisonava08,2864008.0,44a276b405bbaff91137,28504,JWST COSMOS,2.1,2025-04-29 04:07:02+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108665729"":{""retired"":{""id"":140555828,""workf...",108665729,140555828
5,634692959,allisonava08,2864008.0,42f09ae8d31875c1ec95,28504,JWST COSMOS,2.1,2025-04-29 04:07:27+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108682329"":{""retired"":{""id"":140555845,""workf...",108682329,140555845
6,634692987,allisonava08,2864008.0,991590e35312d4bfe394,28504,JWST COSMOS,2.1,2025-04-29 04:07:40+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108657542"":{""retired"":{""id"":140555850,""workf...",108657542,140555850
7,634693016,allisonava08,2864008.0,cfeada996e5d09bac3bc,28504,JWST COSMOS,2.1,2025-04-29 04:07:54+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108640888"":{""retired"":{""id"":140555856,""workf...",108640888,140555856
8,634693079,allisonava08,2864008.0,9925ccdf788b4bd5b14c,28504,JWST COSMOS,2.1,2025-04-29 04:08:22+00:00,NaN,NaN,"{""source"":""api"",""session"":""a35ee2f9ed710ecdb12...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108639693"":{""retired"":{""id"":140555866,""workf...",108639693,140555866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233839,638678466,matarenko,4611.0,ba5506437859818bde30,28504,JWST COSMOS,2.1,2025-05-12 21:40:07+00:00,NaN,NaN,"{""source"":""api"",""session"":""868f99e649941036782...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108637448"":{""retired"":{""id"":140563946,""workf...",108637448,140563946
247415,639146430,Skrigepige,2866196.0,0c4326c47761e8ceb56a,28504,JWST COSMOS,2.1,2025-05-14 10:40:53+00:00,NaN,NaN,"{""source"":""api"",""session"":""93b60151a9d25c70ae7...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108684211"":{""retired"":{""id"":140556169,""workf...",108684211,140556169
247416,639146557,Skrigepige,2866196.0,3438752e24f80b2b55df,28504,JWST COSMOS,2.1,2025-05-14 10:41:23+00:00,NaN,NaN,"{""source"":""api"",""session"":""93b60151a9d25c70ae7...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108673723"":{""retired"":{""id"":140560690,""workf...",108673723,140560690
247417,639146811,Skrigepige,2866196.0,3438752e24f80b2b55df,28504,JWST COSMOS,2.1,2025-05-14 10:42:30+00:00,NaN,NaN,"{""source"":""api"",""session"":""93b60151a9d25c70ae7...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108641303"":{""retired"":{""id"":140556888,""workf...",108641303,140556888
255378,639653984,Exhausted_Amateur,2868359.0,5135dde9ba84140b2138,28504,JWST COSMOS,2.1,2025-05-15 18:55:45+00:00,NaN,NaN,"{""source"":""api"",""session"":""219853831c58099d008...","[{""task"":""T0"",""task_label"":""Is the **central g...","{""108659521"":{""retired"":{""id"":140558126,""workf...",108659521,140558126

In [17]:
clf['annotations'] = clf['annotations'].apply(lambda x: json.loads(x))

In [18]:
clf['annotations'].iloc[0]

[{'task': 'T0',
  'task_label': 'Is the **central galaxy** simply smooth and rounded, with no sign of a disk?',
  'value': '![star.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/cd46dc5a-44b3-426e-82c1-31812ca65a3e.png =60x) Star, Artifact, or Bad Zoom'},
 {'task': 'T19',
  'task_label': 'What problem do you see with the image?',
  'value': '![star.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/cd46dc5a-44b3-426e-82c1-31812ca65a3e.png =60x) Star'}]

In [19]:
df = export_to_responses.explode_annotations(clf, exclude_tasks=['T10'])
df

,task,task_label,value,id_str,user_id,classification_id,created_at,subject_ids
4,T0,Is the **central galaxy** simply smooth and ro...,![star.png](https://panoptes-uploads.zoonivers...,140555828,2864008.0,634692912,2025-04-29 04:07:02+00:00,108665729
4,T19,What problem do you see with the image?,![star.png](https://panoptes-uploads.zoonivers...,140555828,2864008.0,634692912,2025-04-29 04:07:02+00:00,108665729
5,T0,Is the **central galaxy** simply smooth and ro...,![star.png](https://panoptes-uploads.zoonivers...,140555845,2864008.0,634692959,2025-04-29 04:07:27+00:00,108682329
5,T19,What problem do you see with the image?,![bad_zoom_smaller_lens.png](https://panoptes-...,140555845,2864008.0,634692959,2025-04-29 04:07:27+00:00,108682329
6,T0,Is the **central galaxy** simply smooth and ro...,![star.png](https://panoptes-uploads.zoonivers...,140555850,2864008.0,634692987,2025-04-29 04:07:40+00:00,108657542
...,...,...,...,...,...,...,...,...
255378,T6,How tightly wound do the spiral arms appear?,![loose_arms.png](https://panoptes-uploads.zoo...,140558126,2868359.0,639653984,2025-05-15 18:55:45+00:00,108659521
255378,T7,How many spiral arms are there?,![3_arms.png](https://panoptes-uploads.zoonive...,140558126,2868359.0,639653984,2025-05-15 18:55:45+00:00,108659521
255378,T8,"Is there a central bulge? If so, how large is ...",![bulge_icon_obvious_bulge.png](https://panopt...,140558126,2868359.0,639653984,2025-05-15 18:55:45+00:00,108659521
255378,T12,Are there any obvious bright clumps?,![workflow_isnotclumpy.png](https://panoptes-u...,140558126,2868359.0,639653984,2025-05-15 18:55:45+00:00,108659521
255378,T11,Is the galaxy merging or disturbed?,![merger_icons_merger.png](https://panoptes-up...,140558126,2868359.0,639653984,2025-05-15 18:55:45+00:00,108659521

In [20]:
# question = schema.get_question_from_raw_name('T0')
# # question.get_answer_names()
# question.get_raw_answer_names()

In [21]:
cleaned = export_to_responses.clean_exploded_annotations(df, schema)

In [22]:
aggregated = aggregate.responses_to_reduced_votes(cleaned.reset_index(drop=True), schema)

In [23]:
aggregated

question_response,id_str,smooth-or-featured_smooth,smooth-or-featured_featured-or-disk,smooth-or-featured_star-artifact-zoom,how-rounded_round,how-rounded_in-between,how-rounded_cigar-shaped,disk-edge-on_yes,disk-edge-on_no,edge-on-bulge_rounded,...,bulge-size_dominant_fraction,merging_merger_fraction,merging_major-disturbance_fraction,merging_minor-disturbance_fraction,merging_none_fraction,clumps_yes_fraction,clumps_no_fraction,problem_star_fraction,problem_artifact_fraction,problem_bad-zoom_fraction
0,140468011,17,17,6,0,0,0,15,2,9,...,0.000000,0.029412,0.058824,0.235294,0.676471,0.058824,0.941176,0.000000,0.166667,0.833333
1,140468173,25,0,15,0,0,0,0,0,0,...,0.000000,0.000000,0.040000,0.200000,0.760000,0.000000,0.000000,0.133333,0.000000,0.866667
2,140468449,30,6,4,0,0,0,0,6,0,...,0.333333,0.055556,0.055556,0.138889,0.750000,0.000000,1.000000,0.250000,0.000000,0.750000
3,140469172,30,4,6,0,0,0,0,4,0,...,0.250000,0.000000,0.088235,0.147059,0.764706,0.000000,1.000000,0.000000,0.000000,1.000000
4,140508541,16,16,8,0,0,0,14,2,6,...,0.000000,0.000000,0.093750,0.218750,0.687500,0.062500,0.937500,0.000000,0.250000,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4704,140564997,5,2,33,0,0,0,0,2,0,...,0.000000,0.571429,0.142857,0.142857,0.142857,0.500000,0.500000,0.060606,0.121212,0.818182
4705,140565001,32,2,7,0,0,0,1,1,1,...,1.000000,0.029412,0.000000,0.205882,0.764706,0.000000,1.000000,0.000000,0.000000,1.000000
4706,140565007,18,9,14,0,0,0,0,9,0,...,0.111111,0.703704,0.037037,0.037037,0.222222,0.666667,0.333333,0.000000,0.000000,1.000000
4707,140565008,21,0,20,0,0,0,0,0,0,...,0.000000,0.047619,0.000000,0.095238,0.857143,0.000000,0.000000,0.350000,0.000000,0.650000
4708,140565009,27,3,10,0,0,0,1,2,1,...,0.500000,0.000000,0.033333,0.033333,0.933333,0.333333,0.666667,0.600000,0.000000,0.400000

In [24]:
# merge in subject data

final = pd.merge(
    aggregated,
    clf[['id_str', 'subject_ids']].drop_duplicates(),
    on='id_str',
    how='left'
)
final = final.rename(columns={'subject_ids': 'subject_id'})
 # big 4GB csv
subject_df = pd.read_csv('/home/walml/repos/gz-panoptes-reduction/data/euclid/galaxy-zoo-subjects.csv', usecols=['subject_id', 'locations'])
final = final.merge(subject_df, on='subject_id', how='left')

final['subject_id'].isna().mean()

0.0

In [25]:
final['locations']

0        {"0":"https://panoptes-uploads.zooniverse.org/...
1        {"0":"https://panoptes-uploads.zooniverse.org/...
2        {"0":"https://panoptes-uploads.zooniverse.org/...
3        {"0":"https://panoptes-uploads.zooniverse.org/...
4        {"0":"https://panoptes-uploads.zooniverse.org/...
                               ...
10804    {"0":"https://panoptes-uploads.zooniverse.org/...
10805    {"0":"https://panoptes-uploads.zooniverse.org/...
10806    {"0":"https://panoptes-uploads.zooniverse.org/...
10807    {"0":"https://panoptes-uploads.zooniverse.org/...
10808    {"0":"https://panoptes-uploads.zooniverse.org/...
Name: locations, Length: 10809, dtype: object

In [26]:
final['url_first_frame'] = final['locations'].apply(lambda x: json.loads(x)["0"])
final['url_second_frame'] = final['locations'].apply(lambda x: json.loads(x)["1"])

In [27]:
final['url_first_frame'].iloc[-1]

'https://panoptes-uploads.zooniverse.org/subject_location/be4a888d-1521-4e44-851b-15c33d42a8b4.png'

In [28]:
final['url_second_frame'].iloc[-1]

'https://panoptes-uploads.zooniverse.org/subject_location/b49ccd32-ed1d-4433-a48a-4df2283eb7c8.png'

In [29]:
final.to_csv(aggregated_loc, index=False)

In [30]:
final['smooth-or-featured_smooth_fraction']

0        0.425000
1        0.425000
2        0.425000
3        0.625000
4        0.625000
           ...
10804    0.439024
10805    0.512195
10806    0.512195
10807    0.675000
10808    0.675000
Name: smooth-or-featured_smooth_fraction, Length: 10809, dtype: float64